[platformio]
default_envs = m5stack-atom-lite

[env:m5stack-atom-lite]
platform = espressif32@6.6.0
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
lib_deps =
    khoih-prog/Ethernet_Generic@^2.8.1
    bblanchon/ArduinoJson@^7.4.2
    someweisguy/esp_dmx@^4.1.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINOJSON_USE_LONG_LONG=1
    -DUSE_ETHERNET_GENERIC=1
    -DUSE_THIS_SS_PIN=19
